#!/usr/bin/env python3
"""Project-scoped Codex integration. Python 3.11+, stdlib only; never edits user config."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tomllib
from datetime import datetime, timezone

CORE = Path(__file__).resolve().parents[1]
BEGIN = "<!-- XGameHarness:begin -->"
END = "<!-- XGameHarness:end -->"
PACKS = {"game-studio-core", "unreal-pack", "blender-pack"}
IDENTITY_KEY = r"[a-z][a-z0-9_-]*"
NEEDS_ROSTER = """NEEDS-ROSTER .claude/team.json
名册由服务器／管理员下发，本地不自注册：拿当前机器的 git 配置替你登记，换一台机器就会解析成 unknown。
按项目形态三选一取得：
  1. 单仓项目 —— 让管理员把 .claude/team.json 提交进本仓，git pull 即可。
  2. 接了文档仓 —— python harness.py roster --project . --from <docs-repo-url>
  3. 不接工作室服务器 —— 照 project-template/.claude/team.json.template 手写，
     git_users 与 git_emails 两个字段都要填；只填其一，换机器或改 git 配置必断。
其余项目文件已写好；补上名册后重跑 doctor。"""


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def git(root: Path, *args: str) -> str:
    result = subprocess.run(["git", "-C", str(root), *args], capture_output=True,
                            encoding="utf-8", errors="replace", timeout=10)
    return result.stdout.strip() if result.returncode == 0 else ""


def git_strict(root: Path, *args: str, timeout: int = 60) -> str:
    """Network-capable git: raises instead of swallowing, and returns stdout verbatim."""
    result = subprocess.run(["git", "-C", str(root), *args], capture_output=True,
                            encoding="utf-8", errors="replace", timeout=timeout)
    if result.returncode != 0:
        detail = result.stderr.strip() or f"exit {result.returncode}"
        raise ValueError(f"git {' '.join(args)} failed: {detail}")
    return result.stdout


def project_root(cwd: str | Path) -> Path:
    path = Path(cwd).resolve()
    # A project boundary wins over a parent monorepo root.
    for parent in (path, *path.parents):
        if ((parent / ".codex/harness.json").is_file()
                or (parent / ".claude/settings.json").is_file()
                or (parent / ".claude/team.json").is_file()):
            return parent
        if (parent / ".git").exists():
            return parent
    return path


def safe_path(root: Path, relative: str) -> Path:
    target = (root / relative).resolve()
    if not target.is_relative_to(root.resolve()):
        raise ValueError(f"Path escapes project: {relative}")
    return target


def load_json(path: Path, default=None):
    return json.loads(read(path)) if path.is_file() else ({} if default is None else default)


def identity(root: Path) -> str | None:
    team = load_json(root / ".claude/team.json")
    user, email = git(root, "config", "user.name"), git(root, "config", "user.email")
    for field, value in (("git_users", user), ("git_emails", email)):
        if not value:
            continue
        for key, entry in team.get("identities", {}).items():
            if value in entry.get(field, []) and re.fullmatch(IDENTITY_KEY, key):
                return key
    return None


def agent_toml(source: Path, pack: str) -> str:
    text = read(source)
    _, header, body = text.split("---", 2)
    desc = re.search(r"^description:\s*(.+)$", header, re.M)
    description = desc.group(1).strip().strip('"\'') if desc else source.stem
    # The role body is shared, while Claude's tool/memory/model metadata is not.
    body = re.sub(r"> \*\*Roster note\*\*:.*?(?=\n### |\n## )", "", body, flags=re.S)
    body = body.replace("${CLAUDE_PLUGIN_ROOT}", str(source.parents[1]).replace("\\", "/"))
    preface = (
        "Follow the current task and project AGENTS.md. This is a Codex specialist role. "
        "Use available Codex tools; Claude tool names in the shared role text describe capabilities, "
        "not callable APIs. Do not assume a Skill tool, user-memory feature, or nested delegation. "
        "Return evidence and unresolved decisions to the parent. Complete authorized work without "
        "waiting for another approval merely because the legacy role text says ask. "
        "Durable project context lives in team/session-state and docs/architecture. "
        "Do not edit personal Codex memory. Delegate only when authorized and tools are available.\n\n"
    )
    name = pack + "--" + source.stem
    return ("# Generated by XGameHarness; local edits are preserved by hash tracking.\n"
            + f"name = {json.dumps(name)}\n"
            + f"description = {json.dumps(description, ensure_ascii=False)}\n"
            + f"developer_instructions = {json.dumps(preface + body.strip(), ensure_ascii=False)}\n")


class Writer:
    def __init__(self, root: Path, state: dict, dry_run: bool):
        self.root, self.state, self.dry_run = root, state, dry_run
        self.hashes = state.setdefault("managedFiles", {})
        self.actions: list[str] = []
        self.conflicts: list[str] = []

    def write(self, rel: str, content: str, managed=False, rule=False):
        path = safe_path(self.root, rel)
        old = read(path) if path.exists() else None
        if old == content:
            if managed:
                self.hashes[rel] = digest(content)
            return
        allowed = old is None or (managed and self.hashes.get(rel) == digest(old))
        if rule and old is not None:
            # Existing contract: removing managed-by pins a customized rule.
            header = old.split("---", 2)[1] if old.startswith("---") else ""
            source_header = content.split("---", 2)[1]
            marker = re.search(r"^managed-by:\s*(.+)$", source_header, re.M)
            allowed = bool(marker and re.search(
                r"^managed-by:\s*" + re.escape(marker.group(1)) + r"\s*$", header, re.M))
        if not allowed:
            self.conflicts.append(rel)
            self.actions.append("PRESERVE customized " + rel)
            return
        self.actions.append(("CREATE " if old is None else "UPDATE ") + rel)
        if not self.dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
        if managed:
            self.hashes[rel] = digest(content)

    def merge_block(self, content: str):
        path = safe_path(self.root, "AGENTS.md")
        old = read(path) if path.exists() else ""
        block = f"{BEGIN}\n{content.rstrip()}\n{END}"
        if BEGIN in old or END in old:
            if old.count(BEGIN) != 1 or old.count(END) != 1 or old.index(BEGIN) > old.index(END):
                raise ValueError("AGENTS.md has malformed XGameHarness markers")
            original = old[old.index(BEGIN):old.index(END) + len(END)]
            if original != block and self.state.get("agentsBlockHash") != digest(original):
                self.conflicts.append("AGENTS.md managed block")
                self.actions.append("PRESERVE customized AGENTS.md block")
                return
            new = old.replace(original, block)
        else:
            new = old.rstrip() + ("\n\n" if old else "") + block + "\n"
        if new != old:
            self.actions.append("MERGE AGENTS.md")
            if not self.dry_run:
                path.write_text(new, encoding="utf-8", newline="\n")
        self.state["agentsBlockHash"] = digest(block)


def sync(args) -> int:
    root = Path(args.project).resolve()
    if not root.is_dir():
        raise ValueError("--project must be an existing directory")
    state_path = safe_path(root, ".codex/harness.json")
    state = load_json(state_path)
    roots = [CORE]
    ue = args.unreal_root or state.get("sources", {}).get("unreal-pack")
    if ue:
        roots.append(Path(ue).resolve())
    blender = args.blender_root or state.get("sources", {}).get("blender-pack")
    if blender:
        roots.append(Path(blender).resolve())
    # Key everything by the manifest name: the installed cache directory is a version
    # string, so a directory name silently loses the pack on the next sync.
    packs: list[tuple[Path, dict]] = []
    for pack in roots:
        manifest = load_json(pack / ".codex-plugin/plugin.json")
        if manifest.get("name") not in PACKS:
            raise ValueError(f"Not an XGameHarness pack: {pack}")
        packs.append((pack, manifest))
    writer = Writer(root, state, args.dry_run)
    # Validate merge markers before any writes.
    agents_path = safe_path(root, "AGENTS.md")
    old_agents = read(agents_path) if agents_path.exists() else ""
    if BEGIN in old_agents or END in old_agents:
        if old_agents.count(BEGIN) != 1 or old_agents.count(END) != 1 or old_agents.index(BEGIN) > old_agents.index(END):
            raise ValueError("AGENTS.md has malformed XGameHarness markers")
    for pack, manifest in packs:
        for source in sorted((pack / "rules").glob("*.md")):
            writer.write(".claude/rules/" + source.name, read(source), rule=True)
        if args.command == "sync-rules":
            continue
        for source in sorted((pack / "agents").glob("*.md")):
            content = agent_toml(source, manifest["name"])
            tomllib.loads(content)  # validate before writing
            writer.write(f".codex/agents/{manifest['name']}--{source.stem}.toml", content, managed=True)
    if args.command != "sync-rules":
        # The roster is never fabricated here; see NEEDS_ROSTER and the roster subcommand.
        if not (root / ".claude/settings.json").exists():
            # Claude resolves enabledPlugins only from settings.json; without it neither
            # runtime-shared rules nor any skill loads on the Claude side. Guarded by
            # exists() rather than handed to Writer: teams customize permissions here,
            # and an unmanaged entry would print PRESERVE on every later sync.
            settings = json.loads(read(CORE / "project-template/.claude/settings.json"))
            settings["enabledPlugins"] = {m["name"] + "@XGameHarness": True for _, m in packs}
            writer.write(".claude/settings.json",
                         json.dumps(settings, ensure_ascii=False, indent=2) + "\n")
        if not (root / "plan/stage.md").exists():
            writer.write("plan/stage.md", read(CORE / "docs/templates/stage.md").replace("[日期]", datetime.now().date().isoformat()))
        if not (root / "CLAUDE.md").exists():
            writer.write("CLAUDE.md", read(CORE / "project-template/CLAUDE.md").replace("<ProjectName>", root.name))
        writer.write(".codex/xgameharness.md", read(CORE / "docs/codex-runtime.md"), managed=True)
        # Keep project knowledge discoverable even before hook trust is granted.
        writer.merge_block(
            "## XGameHarness (Codex + Claude Code)\n\n"
            "默认中文交流。执行本项目任务前读取 `.codex/xgameharness.md`；需要引擎信息时读取\n"
            "项目已有 `CLAUDE.md` 的 Technology Stack 和 `docs/engine-reference/`。\n"
            "编辑前按 `.claude/rules/*.md` 的 `paths` 选择并读取相关规则；此目录是两个运行时\n"
            "共用的项目数据，不要求安装 Claude。规则正文按需加载，不全量灌入上下文。\n"
            "跨会话状态放在 `team/session-state/{identity}/`，身份从 `.claude/team.json` 解析。\n"
            "恢复时核验 Git 和实际文件，旧的计划不是当前事实。提交、推送按用户授权执行。\n"
            "已授权的日常修改直接完成并验证；仅在缺少必要信息或需要新增授权时询问。\n"
            "插件提供的专家通过 `.codex/agents/` 使用，名称为 `<pack>--<role>`。\n"
            "按当前宿主的委派权限执行；没有自定义 agent 接口时读取角色文件，自行执行或\n"
            "把角色内容传给可用的通用子 agent，不调用不存在的 Claude Agent/Skill API。"
        )
        ignore = safe_path(root, ".gitignore")
        content = read(ignore) if ignore.exists() else ""
        wanted = (".codex/state/", ".claude/state/", ".claude/settings.local.json", "__pycache__/")
        additions = [line for line in wanted if line not in content.splitlines()]
        if additions:
            writer.actions.append("MERGE .gitignore")
            if not args.dry_run:
                body = content.rstrip()
                ignore.write_text((body + "\n" if body else "") + "\n".join(additions) + "\n",
                                  encoding="utf-8")
        state["schemaVersion"] = 1
        state["sources"] = {m["name"]: str(p) for p, m in packs}
        state["versions"] = {m["name"]: m["version"] for _, m in packs}
    if not args.dry_run:
        state_path.parent.mkdir(parents=True, exist_ok=True)
        state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("\n".join(writer.actions) or "Already up to date")
    if writer.conflicts:
        print("Customized files preserved; review differences before merging.")
    if args.command != "sync-rules" and not (root / ".claude/team.json").is_file():
        # Everything else is written; rolling back would leave a half-configured project.
        # Exit 3 = files are in place, one external thing is missing. 1 stays for faults.
        print(NEEDS_ROSTER, file=sys.stderr)
        return 3
    return 0


def roster(args) -> int:
    """Fetch the roster over git. The local copy is a cache; the server/admin owns it."""
    root = Path(args.project).resolve()
    if not root.is_dir():
        raise ValueError("--project must be an existing directory")
    state_path = safe_path(root, ".codex/harness.json")
    state = load_json(state_path)
    remote = args.source or state.get("roster", {}).get("remote")
    if not remote:
        raise ValueError("No roster remote recorded; pass --from <docs-repo-url> once")
    cache = safe_path(root, ".codex/state/roster")
    if not (cache / "HEAD").is_file():
        cache.mkdir(parents=True, exist_ok=True)
        git_strict(cache, "init", "--bare", "--quiet")
    git_strict(cache, "fetch", "--depth", "1", "--quiet", remote, args.ref)
    content = git_strict(cache, "show", "FETCH_HEAD:.claude/team.json")
    try:
        data = json.loads(content)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Roster at {remote} is not valid JSON ({exc}); local copy untouched") from exc
    identities = data.get("identities")
    if not isinstance(identities, dict) or not identities:
        raise ValueError("Roster has no identities; local copy untouched")
    for key in identities:
        if not re.fullmatch(IDENTITY_KEY, key):
            raise ValueError(f"Roster identity key {key!r} must match {IDENTITY_KEY}; local copy untouched")
    if args.source and not args.dry_run:
        state.setdefault("roster", {})["remote"] = args.source
        state_path.parent.mkdir(parents=True, exist_ok=True)
        state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    target = safe_path(root, ".claude/team.json")
    old = read(target) if target.is_file() else None
    payload = content if content.endswith("\n") else content + "\n"
    if old == payload:
        print("Roster already current")
        return 0
    # Deliberately not a Writer.write: authority lives in the remote, so a locally edited
    # copy is overwritten rather than preserved — same rule the server applies to the
    # admin-delivered files it owns. Local edits belong upstream, not here.
    print(("CREATE " if old is None else "OVERWRITE ") + ".claude/team.json"
          + (f" (本地副本是缓存，权威在 {remote})" if old is not None else ""))
    if not args.dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(payload, encoding="utf-8", newline="\n")
    return 0


def doctor(root: Path) -> int:
    issues = []
    for rel in ("AGENTS.md", ".codex/xgameharness.md", ".codex/harness.json",
                ".claude/settings.json", ".claude/team.json", "plan/stage.md"):
        if not (root / rel).is_file():
            issues.append("MISSING " + rel)
    state = load_json(root / ".codex/harness.json")
    for relative in state.get("managedFiles", {}):
        if not safe_path(root, relative).is_file():
            issues.append("MISSING managed file " + relative)
    for pack, source in state.get("sources", {}).items():
        if not (Path(source) / ".codex-plugin/plugin.json").is_file():
            issues.append("STALE source " + pack + ": rerun init from the installed plugin")
    for path in sorted((root / ".codex/agents").glob("*.toml")):
        try:
            data = tomllib.loads(read(path))
            if not all(data.get(key) for key in ("name", "description", "developer_instructions")):
                issues.append("INVALID agent " + path.name)
        except tomllib.TOMLDecodeError as exc:
            issues.append(f"INVALID {path.name}: {exc}")
    who = identity(root)
    if who is None:
        issues.append("IDENTITY unresolved; ask the roster owner to add this git account "
                      "to .claude/team.json (automatic writes disabled)")
    if not list((root / ".claude/rules").glob("*.md")):
        issues.append("MISSING shared rules")
    print("\n".join(issues) if issues else f"Project contract OK; identity={who}")
    print("Hook trust, plugin installation and engine execution must be checked in the host; this check does not prove them.")
    return 1 if issues else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["init", "sync", "sync-rules", "roster", "doctor"])
    parser.add_argument("--project", default=".")
    parser.add_argument("--unreal-root", help="Exact enabled unreal-pack root; never pick a cached version by mtime")
    parser.add_argument("--blender-root", help="Exact enabled blender-pack root; opt-in modeling roles")
    parser.add_argument("--from", dest="source", help="Roster repository URL or path; recorded for later roster runs")
    parser.add_argument("--ref", default="HEAD", help="Roster ref to fetch (default HEAD)")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.command == "doctor":
        return doctor(project_root(args.project))
    return roster(args) if args.command == "roster" else sync(args)


if __name__ == "__main__":
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")
    try:
        sys.exit(main())
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        print(f"XGameHarness: {exc}", file=sys.stderr)
        sys.exit(1)
